version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./config.json:/app/config.json"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1