version: '3.8'

services:
  app:
    image: "ghcr.io/sydowma/codereviewbot:master"
    volumes:
      - "./config.json:/app/config.json"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1